name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      file_changed: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          workflows:
            - '.github/workflows/**'
            - 'Software/**'
    # run only if 'workflows' files were changed
    - name: workflow tests
      if: steps.filter.outputs.workflows == 'true'
      run: echo "File changed"

    # run only if not 'workflows' files were changed
    - name: not workflow tests
      if: steps.filter.outputs.workflows != 'true'
      run: echo "No file changed"

  conditional_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32s3
        path: './Software'
        
    - name: List build artefacts
      run: |
        ls -l ./Software/build/

    - name: Zip Firmware
      run: |
        cd ./Software/build
        zip /tmp/Firmware-${GITHUB_REF#refs/tags/}.zip ./bootloader/bootloader.bin ./partition_table/partition-table.bin sauvc-idf-only.bin    
          
    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Firmware${GITHUB_REF#refs/tags/}.zip
        path: |
          /tmp/Firmware${GITHUB_REF#refs/tags/}.zip
