name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: v3.3.1
        path: './Hardware'
        
    - name: List build artefacts
      run: |
        ls -l build/
    
    - name: Store Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SAUVC_2025.bin 
        path: |
          build/SAUVC_2025.bin