name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32s3
        path: './Software'
        
    - name: List build artefacts
      run: |
        ls -l ./Software/build/
    
    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SAUVC_2025.bin 
        path: |
          ./Software/build/sauvf-idf-only.bin