name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      file_changed: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
              - 'Software/**'
      - name: workflow tests
        if: steps.filter.outputs.workflows == 'true'
        run: echo "File changed"
      - name: not workflow tests
        if: steps.filter.outputs.workflows != 'true'
        run: echo "No file changed"

  conditional_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32s3
          path: './Software'
        
      - name: List build artefacts
        run: ls -l ./Software/build/

      - name: Zip Firmware
        id: zip_firmware
        run: |
          cd ./Software/build
          # Check if GITHUB_REF is a tag reference (e.g., refs/tags/v1.0)
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            tag=${GITHUB_REF#refs/tags/}
            firmware_zip="/tmp/Firmware_${tag}.zip"
          else
            commit_sha=$(git rev-parse --short HEAD)
            firmware_zip="/tmp/Firmware_${commit_sha}.zip"
          fi
          echo "Creating zip file: $firmware_zip"
          zip "$firmware_zip" ./bootloader/bootloader.bin ./partition_table/partition-table.bin sauvc-idf-only.bin
          echo "firmware_zip=$firmware_zip" >> $GITHUB_OUTPUT

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Firmware
          path: ${{ steps.zip_firmware.outputs.firmware_zip }}
